# Generated by Django 6.0.3 on 2026-03-28 08:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('media_management', '0002_mediaasset_file_mediaasset_preview_image'),
        ('payments', '0003_payment_checkout_request_id_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DownloadEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('downloaded_at', models.DateTimeField(auto_now_add=True)),
                ('media_asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='download_events', to='media_management.mediaasset')),
                ('payment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='download_events', to='payments.payment')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='download_events', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-downloaded_at',),
            },
        ),
    ]
