# Generated by Django 6.0.3 on 2026-03-23 10:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=255)),
                ('service_type', models.CharField(blank=True, max_length=100)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('in_review', 'In Review'), ('processing', 'Processing'), ('ready', 'Ready'), ('completed', 'Completed')], default='pending', max_length=20)),
                ('shoot_date', models.DateField(blank=True, null=True)),
                ('description', models.TextField(blank=True)),
                ('cover_image_url', models.URLField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-shoot_date', '-updated_at', '-created_at'),
                'constraints': [models.UniqueConstraint(fields=('client', 'slug'), name='unique_client_project_slug')],
            },
        ),
    ]
