# Generated by Django 6.0.3 on 2026-04-08 17:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Service",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=120)),
                ("slug", models.SlugField(max_length=140, unique=True)),
                ("badge", models.CharField(max_length=160)),
                ("heading", models.CharField(max_length=255)),
                ("description", models.TextField()),
                (
                    "included_items",
                    models.TextField(
                        blank=True, help_text="One included item per line."
                    ),
                ),
                (
                    "best_for_items",
                    models.TextField(
                        blank=True, help_text="One best-fit use case per line."
                    ),
                ),
                ("packages_heading", models.CharField(max_length=160)),
                ("book_label", models.CharField(max_length=160)),
                ("booking_service", models.CharField(max_length=120)),
                ("teaser", models.CharField(max_length=255)),
                ("icon", models.CharField(blank=True, max_length=16)),
                ("display_order", models.PositiveIntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ("display_order", "name"),
            },
        ),
        migrations.CreateModel(
            name="ServicePackage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=160)),
                (
                    "price_label",
                    models.CharField(
                        help_text="Examples: KES 12,000 or Custom Quote", max_length=80
                    ),
                ),
                ("description", models.TextField()),
                ("highlighted", models.BooleanField(default=False)),
                ("display_order", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "service",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="packages",
                        to="services.service",
                    ),
                ),
            ],
            options={
                "ordering": ("display_order", "id"),
            },
        ),
    ]
