# Generated by Django 6.0.3 on 2026-04-29 14:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="HeroCarousel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "section_key",
                    models.CharField(
                        choices=[
                            ("home_main", "Homepage Main Hero"),
                            ("home_cta", "Homepage Closing Hero"),
                            ("services_main", "Services Hero"),
                            ("services_empty", "Services Empty Hero"),
                            ("portfolio_list", "Portfolio List Hero"),
                            ("portfolio_detail", "Portfolio Detail Hero"),
                            ("contact_main", "Contact Hero"),
                        ],
                        max_length=40,
                        unique=True,
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        blank=True,
                        help_text="Optional admin label. Defaults to the section name.",
                        max_length=120,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Hero carousel",
                "verbose_name_plural": "Hero carousels",
                "ordering": ("section_key",),
            },
        ),
        migrations.CreateModel(
            name="HeroCarouselSlide",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.ImageField(upload_to="hero_carousels/%Y/%m/%d/")),
                ("alt_text", models.CharField(blank=True, max_length=160)),
                ("display_order", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "carousel",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="slides",
                        to="core.herocarousel",
                    ),
                ),
            ],
            options={
                "verbose_name": "Hero carousel slide",
                "verbose_name_plural": "Hero carousel slides",
                "ordering": ("display_order", "id"),
            },
        ),
    ]
