# Generated by Django 6.0.3 on 2026-05-05 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="HomeGalleryItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "section",
                    models.CharField(
                        choices=[
                            ("photography", "Homepage Photography Gallery"),
                            ("videography", "Homepage Videography Gallery"),
                        ],
                        max_length=24,
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        blank=True,
                        help_text="Optional admin label for easier recognition.",
                        max_length=120,
                    ),
                ),
                ("image", models.ImageField(upload_to="home_gallery/%Y/%m/%d/")),
                ("alt_text", models.CharField(blank=True, max_length=160)),
                (
                    "project_slug",
                    models.CharField(
                        blank=True,
                        help_text="Optional portfolio project slug to open when this image is clicked.",
                        max_length=80,
                    ),
                ),
                ("display_order", models.PositiveIntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Homepage gallery item",
                "verbose_name_plural": "Homepage gallery items",
                "ordering": ("section", "display_order", "id"),
            },
        ),
    ]
