# Generated by Django 6.0.3 on 2026-05-08 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_homegalleryitem"),
    ]

    operations = [
        migrations.CreateModel(
            name="AboutTeamMember",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=120)),
                ("role", models.CharField(max_length=120)),
                ("image", models.ImageField(upload_to="about_team/%Y/%m/%d/")),
                ("alt_text", models.CharField(blank=True, max_length=160)),
                ("display_order", models.PositiveIntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "About team member",
                "verbose_name_plural": "About team members",
                "ordering": ("display_order", "id"),
            },
        ),
    ]
