# Generated by Django 6.0.3 on 2026-03-26 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("downloads", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="download",
            name="file",
            field=models.FileField(blank=True, upload_to="downloads/%Y/%m/%d/"),
        ),
    ]
