# Generated by Django 6.0.3 on 2026-03-28 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media_management', '0002_mediaasset_file_mediaasset_preview_image'),
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='media_assets',
            field=models.ManyToManyField(blank=True, related_name='payments', to='media_management.mediaasset'),
        ),
    ]
