# Generated by Django 6.0.3 on 2026-05-27 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bookings", "0002_alter_bookingrequest_phone"),
    ]

    operations = [
        migrations.AddField(
            model_name="bookingrequest",
            name="last_progress_notified_status",
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name="bookingrequest",
            name="portal_invite_sent_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="bookingrequest",
            name="progress_notified_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="bookingrequest",
            name="service",
            field=models.CharField(
                choices=[
                    ("Photography", "Photography"),
                    ("Videography", "Videography"),
                    ("Branding", "Branding"),
                    ("Graphic Design", "Graphic Design"),
                    ("Client Portal Demo", "Client Portal Demo"),
                ],
                max_length=50,
            ),
        ),
    ]
