# Generated by Django 6.0.3 on 2026-03-23 10:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MediaAsset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('kind', models.CharField(choices=[('photo', 'Photo'), ('video', 'Video'), ('design', 'Design'), ('document', 'Document')], default='photo', max_length=20)),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('preview_image_url', models.URLField(blank=True)),
                ('file_url', models.URLField(blank=True)),
                ('is_highlight', models.BooleanField(default=False)),
                ('is_edited', models.BooleanField(default=False)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media_files', to='projects.project')),
            ],
            options={
                'ordering': ('-uploaded_at', 'title'),
            },
        ),
    ]
