# Generated by Django 6.0.3 on 2026-03-26 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("media_management", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="mediaasset",
            name="file",
            field=models.FileField(blank=True, upload_to="project_assets/%Y/%m/%d/"),
        ),
        migrations.AddField(
            model_name="mediaasset",
            name="preview_image",
            field=models.ImageField(blank=True, upload_to="previews/%Y/%m/%d/"),
        ),
    ]
